import "./globals.css";
import { Plus_Jakarta_Sans } from 'next/font/google';

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-plus-jakarta-sans', 
});


export const metadata = {
  title: "SEZL - Sirajganj Economic Zone Limited",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${plusJakartaSans.className} bg-white`}>
      <body className="bg-white">
        {children}
      </body>
    </html>
  );
}
